---
# Version options
docker_ce_name: docker-ce
docker_ce_version: 18.09.0
docker_ce_cli_name: docker-ce-cli
docker_ce_cli_version: 18.09.0
docker_containerd_name: containerd.io
docker_containerd_version: 1.2.5

# Service options
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Docker Socket options
docker_socket_user: "{{ ansible_user }}"
docker_socket_group: docker
docker_socket_mode: 770

# apt options
docker_yum_arch: x86_64
docker_yum_gpg_key_url: "https://download.docker.com/linux/centos/gpg"
docker_yum_url: https://download.docker.com/linux/
docker_yum_repository: "https://download.docker.com/linux/centos/7/x86_64/stable/"

# yum variables
epel_repo_url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
